version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:13.11.0
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Yarn build
          command: yarn build
      - run:
          name: Compress artifact
          command: tar -cvzf artifact.tar.gz dist
      - store_artifacts:
          path: artifact.tar.gz
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Find latest artifact URL
          command: |
            curl -H "Circle-Token: ${CIRCLE_TOKEN}" https://circleci.com/api/v1.1/project/github/idanyman/portfolio/latest/artifacts | grep -o 'https[^"]*' > url.txt
      - run:
          name: Download latest artifact tarball and upload to server
          command: |
            curl -H "Circle-Token: ${CIRCLE_TOKEN}" -L $(cat url.txt) -o artifact.tar.gz | scp -P$SSH_PORT artifact.tar.gz $SSH_USER@$SSH_HOST:~
      - run:
          name: Untar artifact and move files to public
          command: |
            ssh $SSH_USER@$SSH_HOST -p $SSH_PORT 'tar -xz -f artifact.tar.gz && mv dist/* public_html/ && rm artifact.tar.gz && rm -rf dist'
      - slack/status:
          only_for_branches: master
orbs:
  slack: circleci/slack@3.4.2
workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build # only deploy once build job has completed
          filters:
            branches:
              only: master # only deploy on the master branch